# Generated by Django 2.2.16 on 2021-10-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20211009_1123'),
        ('reviews', '0005_auto_20211009_1732'),
    ]

    operations = [
    ]
