# Generated by Django 2.2.16 on 2021-10-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20211010_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='review',
        ),
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
