# Generated by Django 2.2.16 on 2021-10-10 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_remove_title_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='titles_review', to='reviews.Review', verbose_name='Отзывы'),
        ),
    ]
