# Generated by Django 2.2.16 on 2021-10-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_title_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
