# Generated by Django 2.2.16 on 2021-10-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_title_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verification_code',
            new_name='confirmation_code',
        ),
    ]
