# Generated by Django 2.2.16 on 2021-10-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_auto_20211011_1552'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='not_me',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, username='me'), name='me_is_unacceptable_name'),
        ),
    ]
