# Generated by Django 2.2.16 on 2021-10-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_auto_20211011_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', max_length=20),
        ),
        migrations.RenameField(
            model_name='title',
            old_name='rating',
            new_name='rating_del',
        ),
    ]
