# Generated by Django 2.2.16 on 2021-10-17 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0023_auto_20211016_1353'),
        ('reviews', '0023_auto_20211016_1113'),
    ]

    operations = [
    ]
