# Generated by Django 2.2.16 on 2021-10-17 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0024_merge_20211017_0730'),
        ('reviews', '0023_auto_20211016_1551'),
    ]

    operations = [
    ]
