# Generated by Django 2.2.16 on 2021-10-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0028_auto_20211017_1258'),
        ('reviews', '0024_merge_20211017_0842'),
    ]

    operations = [
    ]
