# Generated by Django 2.2.16 on 2021-10-20 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0029_merge_20211017_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='title',
            name='rating_del',
        ),
    ]
