# Generated by Django 2.2.16 on 2021-10-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0031_auto_20211019_1456'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='choices',
            field=models.CharField(choices=[('USER', 'User'), ('MODERATOR', 'Moderator'), ('ADMIN', 'Admin')], default='user', max_length=32),
        ),
    ]
