# Generated by Django 2.2.16 on 2021-10-20 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0031_auto_20211019_1354'),
        ('reviews', '0031_auto_20211020_0838'),
    ]

    operations = [
    ]
