# Generated by Django 2.2.16 on 2021-10-19 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0032_auto_20211019_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='choices',
            new_name='role',
        ),
    ]
