# Generated by Django 2.2.16 on 2021-10-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0035_auto_20211020_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role_choices_filed',
            new_name='role',
        ),
    ]
