# Generated by Django 2.2.16 on 2021-10-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0036_auto_20211020_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
