# Generated by Django 2.2.16 on 2021-10-21 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0032_merge_20211020_0758'),
        ('reviews', '0038_auto_20211020_1535'),
    ]

    operations = [
    ]
