# Generated by Django 2.2.16 on 2021-10-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0040_auto_20211022_0956'),
        ('reviews', '0040_auto_20211021_1501'),
    ]

    operations = [
    ]
