# Generated by Django 2.2.16 on 2021-10-23 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0041_auto_20211022_2206'),
        ('reviews', '0041_merge_20211022_1442'),
    ]

    operations = [
    ]
