# Generated by Django 2.2.16 on 2021-10-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0042_merge_20211023_0909'),
        ('reviews', '0042_merge_20211023_0706'),
    ]

    operations = [
    ]
