# Generated by Django 2.2.16 on 2021-10-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0043_merge_20211024_0827'),
        ('reviews', '0043_merge_20211023_2146'),
    ]

    operations = [
    ]
